# Generated by Django 5.1.2 on 2024-11-04 13:10

import app_user.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBioData",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        default=app_user.validators.generate_random_key,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Manager", "Manager"),
                            ("Staff", "Staff"),
                            ("Customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user_position",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Manager", "Manager"),
                            ("Chief", "Chief"),
                            ("Waiter", "Waiter"),
                            ("Accounts", "Accounts"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "MALE"), ("Female", "FEMALE")], max_length=10
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=14,
                        validators=[app_user.validators.validate_phone_number],
                    ),
                ),
                (
                    "nid",
                    models.CharField(
                        max_length=10, validators=[app_user.validators.validate_nid]
                    ),
                ),
                ("street_address", models.TextField()),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=4)),
                ("country", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
