# Generated by Django 5.1.2 on 2024-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="is_worker",
            field=models.BooleanField(default=False),
        ),
    ]
