# Generated by Django 5.1.2 on 2024-11-09 03:02

import app_food.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_user", "0002_userinfo_is_worker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, default="none", max_length=20, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True, default="others", max_length=20, null=True
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        default="others",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_food.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "idMeal",
                    models.PositiveIntegerField(
                        default=app_food.validators.generate_random_key,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("strMeal", models.CharField(max_length=100)),
                ("strArea", models.CharField(blank=True, max_length=50, null=True)),
                ("strMealThumb", models.URLField(blank=True, null=True)),
                ("strDescription", models.TextField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_user.userinfo",
                    ),
                ),
                (
                    "strBrand",
                    models.ForeignKey(
                        blank=True,
                        default="none",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foodBrand",
                        to="app_food.brand",
                    ),
                ),
                (
                    "strCategory",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        default="others",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foodCategory",
                        to="app_food.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="app_food.food",
                    ),
                ),
            ],
        ),
    ]
