# Generated by Django 5.1.2 on 2024-11-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_restuarent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulist",
            name="ingredient1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menulist",
            name="ingredient2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menulist",
            name="ingredient3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menulist",
            name="ingredient4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
