# Generated by Django 5.1.2 on 2024-11-10 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_restuarent", "0002_alter_menulist_ingredient1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menulist",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menuList",
                to="app_restuarent.menu",
            ),
        ),
    ]
