# Generated by Django 5.1.2 on 2024-11-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_restuarent", "0003_alter_menulist_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="bnr_img",
            field=models.URLField(default="none"),
        ),
    ]
