# Generated by Django 5.1.2 on 2024-11-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_restuarent", "0004_banner_bnr_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="FoodMenu",
        ),
        migrations.RenameModel(
            old_name="MenuList",
            new_name="FoodMenuList",
        ),
    ]
