# Generated by Django 5.1.2 on 2024-11-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_restuarent", "0006_menu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.SlugField(
                blank=True, default="menu_slug", max_length=100, unique=True
            ),
        ),
    ]
